export const GROUP_TYPES = [
  { value: 'fraternity',    label: 'Fraternity' },
  { value: 'sorority',      label: 'Sorority' },
  { value: 'sports',        label: 'Sports Team' },
  { value: 'club',          label: 'Club' },
  { value: 'honor_society', label: 'Honor Society' },
  { value: 'professional',  label: 'Professional Organization' },
  { value: 'service',       label: 'Service Organization' },
  { value: 'other',         label: 'Other' },
]

export const TERMS = {
  fraternity: {
    group:   'Chapter',
    member:  'Brother',
    members: 'Brothers',
    mentor:  'Big',
    mentee:  'Little',
    mentees: 'Littles',
    cohort:  'Pledge Class',
    team:    'Family',
    treeTitle: 'Big/Little Family Tree',
  },
  sorority: {
    group:   'Chapter',
    member:  'Sister',
    members: 'Sisters',
    mentor:  'Big',
    mentee:  'Little',
    mentees: 'Littles',
    cohort:  'Pledge Class',
    team:    'Family',
    treeTitle: 'Big/Little Family Tree',
  },
  sports: {
    group:   'Team',
    member:  'Player',
    members: 'Players',
    mentor:  'Veteran',
    mentee:  'Rookie',
    mentees: 'Rookies',
    cohort:  'Season',
    team:    'Line',
    treeTitle: 'Veteran/Rookie Tree',
  },
  club: {
    group:   'Club',
    member:  'Member',
    members: 'Members',
    mentor:  'Mentor',
    mentee:  'Mentee',
    mentees: 'Mentees',
    cohort:  'Cohort',
    team:    'Team',
    treeTitle: 'Mentor/Mentee Tree',
  },
  honor_society: {
    group:   'Chapter',
    member:  'Member',
    members: 'Members',
    mentor:  'Senior Member',
    mentee:  'Initiate',
    mentees: 'Initiates',
    cohort:  'Induction Class',
    team:    'Group',
    treeTitle: 'Mentorship Tree',
  },
  professional: {
    group:   'Chapter',
    member:  'Member',
    members: 'Members',
    mentor:  'Mentor',
    mentee:  'Mentee',
    mentees: 'Mentees',
    cohort:  'Cohort',
    team:    'Team',
    treeTitle: 'Mentorship Tree',
  },
  service: {
    group:   'Chapter',
    member:  'Volunteer',
    members: 'Volunteers',
    mentor:  'Leader',
    mentee:  'Member',
    mentees: 'Members',
    cohort:  'Intake',
    team:    'Committee',
    treeTitle: 'Leadership Tree',
  },
  other: {
    group:   'Group',
    member:  'Member',
    members: 'Members',
    mentor:  'Mentor',
    mentee:  'Mentee',
    mentees: 'Mentees',
    cohort:  'Cohort',
    team:    'Team',
    treeTitle: 'Mentorship Tree',
  },
}

export function getTerminology(type, custom = {}) {
  const base = TERMS[type] || TERMS.other
  return {
    ...base,
    ...(custom.member     ? { member:    custom.member }    : {}),
    ...(custom.members    ? { members:   custom.members }   : {}),
    ...(custom.mentor     ? { mentor:    custom.mentor }    : {}),
    ...(custom.mentee     ? { mentee:    custom.mentee }    : {}),
    ...(custom.mentees    ? { mentees:   custom.mentees }   : {}),
    ...(custom.cohort     ? { cohort:    custom.cohort }    : {}),
    ...(custom.team       ? { team:      custom.team }      : {}),
    ...(custom.treeTitle  ? { treeTitle: custom.treeTitle } : {}),
  }
}
